# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbacc4ca78a0eed027e8be05302090b83ebc5879a1ad759b6c386e2f0f0dc36779b6cce3ad81b0af2a464696c210066e98d86493e06217d40847f3c780c98b06

test:
  secret_key_base: 4c193dd33355864eaac9b47156130a1cac4c2881f4f219892daf38bf5915b54e6544420136df3055a5a2fbf67d5382f28eba7a2dd36140916b1743f75695a10f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
